  development:
    adapter: postgresql
    encoding: unicode
    database: endoha_development
    pool: 5
    username: postgres
    password: danjegay

  test:
    adapter: postgresql
    encoding: unicode
    database: endoha_test
    pool: 5
    username: postgres
    password: danjegay
