# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fdde7bc37f856fd2d767811de4e4a030e3f3af31fa37f1d646947029927b3b2f7222274dd2d925e723fcfd975559bb8b7057362fab1e653b2eb084fa417902d

test:
  secret_key_base: a2490f9bc35001ef42e88edca65b5af4bf398524d4ce0303a966cf6e875cb6f7bbadbc9f47cb562468f6e028ad2d45a5c7a35a538b8b8d66b32913e3c9def0e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
